name: Metrics

on:
  schedule:
    - cron: "15 5 * * *"
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - ".github/workflows/metrics.yml"

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: Hashim1999164
          filename: github-metrics.svg

      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: Hashim1999164
          filename: metrics.plugin.isocalendar.fullyear.svg
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
